/**
* @File Name : NameofDayBetweenTwoDates .cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : December 26, 2024
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | December 26, 2024 |   | Initial Version
**/

public class NameofDayBetweenTwoDates  {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}